#!/bin/sh
#
user=$1
port=${2%:*}
portname=${2#*:}
servername=${portname}
if [ ! -z "$host" ]
then
  servername=${host}:${portname}
fi
CURRENT_LOGFILE=/logs/${servername}.log
touch $CURRENT_LOGFILE
coredir="/logs/coredumps/${servername}"
mkdir -p $coredir
cd $coredir
chown $(id -u $user):$(id -g $user) $CURRENT_LOGFILE
chown $(id -u $user):$(id -g $user) $coredir
while [ 1 = 1 ]
do
  . /etc/profile
  echo `date`, server process starting >> $CURRENT_LOGFILE

  ulimit -c 1000000
  su -s /bin/sh -c "$MDSPLUS_DIR/bin/mdsip -p $port -s -h /etc/mdsip.hosts >> $CURRENT_LOGFILE 2>&1" $user
  status=$?
  #/usr/local/cmod/sbin/kill_mdsip_orphans
  echo `date`, server process stopped with status $status >> $CURRENT_LOGFILE
  sleep 5
done
