#!/bin/bash
#
# OS environment variables:
#
export JDK_DIR=/etc/alternatives/java_sdk_openjdk;
#
set -e
case "$1" in
    build)
	if [ -z "$2" ]
	then tag=stable;
	else tag=$2;
	fi;
	if [ -d /source ]
	then
	    tag="local"
	    export BRANCH=local_release 
	    rsync -a /source/ /buildsrc/
	else
	    mkdir -p /buildsrc;
	    cd /buildsrc
	    wget -q -O - https://github.com/MDSplus/mdsplus/archive/${tag}.tar.gz | tar zxf -;
	    mv mdsplus-${tag}/* ./
	fi
	export $(echo $tag | awk -F- '{print "BRANCH="$1" MAJOR="$2" MINOR="$3" RELEASE="$4" NF="NF;}')
	if [ -z "${RELEASE}" ]
	then
	    export RELEASE=0
	fi
	if [ -z "${MINOR}" ]
	then
	    export MINOR=0
	fi
	if [ -z "${MAJOR}" ]
	then
	    export MAJOR=0
	fi
	if [ "${BRANCH:${#BRANCH}-8}" = "_release" ]
	then
	    export BRANCH=${BRANCH:0:${#BRANCH}-8}
	fi
	export PATH=/buildsrc/deploy:$PATH
	build_windows_mdsplus
	;;
    build_latest_release)
	export BRANCH="$2"
	if [ "${BRANCH}" = "stable" ]
	then
	    BNAME=""
	else
	    BNAME="-${BRANCH}"
	fi
	tag=$(wget -O - -q https://github.com/MDSplus/mdsplus/releases | grep ${BRANCH}_release| awk '{print $0; exit;}' | awk -F/ '{print $NF}' | awk -F\" '{print $1}')
	
	export $(echo $tag | awk -F- '{print "MAJOR="$2" MINOR="$3" RELEASE="$4" NF="NF;}')
	if [ -d /installer ]
	then
	    export INSTALLER="/installer/MDSplus${BNAME}-${MAJOR}.${MINOR}-${RELEASE}.exe"
	    if [ -r ${INSTALLER} ]
	    then
		echo "Installer for release $tag already exists so nothing to do."
		exit 0
	    fi
	fi
	mkdir -p /buildsrc;
	cd /buildsrc
	wget -q -O - https://github.com/MDSplus/mdsplus/archive/${tag}.tar.gz | tar zxf -;
	mv mdsplus-${tag}/* ./
	build_windows_mdsplus
	;;
*) echo Unknown option. Valid options are '"build"';;
esac
