#!/bin/bash
#
# OS environment variables:
#
export JDK_DIR=/etc/alternatives/java_sdk_openjdk;
#
set -e
case "$1" in
build)
 if [ -z "$2" ]
 then tag=stable;
 else tag=$2;
 fi;
 if [ -d /source ]
 then 
   rsync -a /source/ /buildsrc/
 else
   mkdir -p /buildsrc;
   wget -q -O - https://github.com/MDSplus/mdsplus/archive/${tag}.tar.gz | tar zxf -;
   mv mdsplus-${tag}/* ./
 fi
 export PATH=/buildsrc/deploy:$PATH
 build_windows_mdsplus
 ;;
*) echo Unknown option. Valid options are '"build"';;
esac
