


FROM dock0/arch:latest


# To build docker image:
#
#

# ENV http_proxy 'eproxy2.rfx.local:8080'
# ENV https_proxy 'eproxy2.rfx.local:8080'

RUN pacman -Sy --noconfirm; \
    pacman -S --noconfirm \
           rsync wget git tar gzip \
           gcc make



