from fedora:21

RUN yum install -y wget make tar \
      mingw32-gcc mingw32-gcc-c++ mingw32-gcc-gfortran mingw32-libxml2 \
      mingw32-dlfcn mingw32-winpthreads mingw32-curl mingw32-readline \
      mingw32-bintools \
      mingw64-gcc mingw64-gcc-c++ mingw64-gcc-gfortran mingw64-libxml2 \
      mingw64-dlfcn mingw64-winpthreads mingw64-curl mingw64-readline \
      mingw64-bintools \
      java-devel libxml2-devel binutils rsync
     

