#!/bin/bash
set -o verbose
set -e 
wget -q -O - https://github.com/MDSplus/3rd-party-apis/archive/master.tar.gz | (cd /; tar zxf -)
mkdir -p /buildroot
cd /buildsrc
./configure --prefix=/buildroot/usr/local/mdsplus \
            --exec_prefix=/buildroot/usr/local/mdsplus \
            --with-labview=/3rd-party-apis-master/labview \
            --with-jdk=$JDK_DIR \
            --with-idl=/3rd-party-apis-master/idl \
            --with-gsi=/usr:gcc64 \
            --bindir=/buildroot/usr/local/mdsplus/bin64 \
            --libdir=/buildroot/usr/local/mdsplus/lib64 \
            --host=x86-64-linux \
            --with-java_target=6 --with-java_bootclasspath=$(pwd)/rt.jar;
make clean > /dev/null
env LANG=en_US.UTF-8 make
make install
make clean >/dev/null;
./configure --prefix=/buildroot/usr/local/mdsplus \
            --exec_prefix=/buildroot/usr/local/mdsplus \
            --with-labview=/3rd-party-apis-master/labview \
            --with-jdk=$JDK_DIR \
            --with-idl=/3rd-party-apis-master/idl \
            --with-gsi=/usr:gcc32 \
            --bindir=/buildroot/usr/local/mdsplus/bin32 \
            --libdir=/buildroot/usr/local/mdsplus/lib32 \
            --host=i686-linux \
            --with-java_target=6 --with-java_bootclasspath=$(pwd)/rt.jar;
env LANG=en_US.UTF-8 make;
env MDSPLUS_VERSION=mdsplus${BNAME}-${MAJOR}-${MINOR}-${RELEASE} make install
make clean >/dev/null;
if [ -d /installer ]
then
    echo "Building rpms"
    if [ -r /certs/rpm-signing-keys.tgz ]
    then
       pushd ${HOME}
        tar zxf /certs/rpm-signing-keys.tgz
       popd
    fi    
    build_rpms_mdsplus
fi
