#!/bin/bash
#
set -e
if [ -x /mdsplus/source/deploy/build_mdsplus ]
then
    /mdsplus/source/deploy/build_mdsplus $@
else
    wget -q --no-check-certificate -O /tmp/build_mdsplus https://github.com/MDSplus/mdsplus/raw/alpha/deploy/build_mdsplus
    chmod a+x /tmp/build_mdsplus
    /tmp/build_mdsplus $@
fi
